/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.ProductoData;
import entidades.Producto;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class menu extends javax.swing.JFrame {
private DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        cargarCabezera();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpBotonProductos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpBotonConsultas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpBotonProveedores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpBotonCompra = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelProveedores = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        PanelCompra = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        PanelConsultas = new javax.swing.JPanel();
        PanelProducto = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtidProducto = new javax.swing.JTextField();
        jtDescripcion = new javax.swing.JTextField();
        jtNombreProducto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaProducto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jCEstado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        menuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ELECTRONICS");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 320, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m_provemaxlogo150.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 190, 120));

        menuPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 130));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SISTEMA DE COMPRA");
        menuPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 830, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wavy-blue-background-free-vector.jpg"))); // NOI18N
        menuPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 130));

        jPanel1.setBackground(new java.awt.Color(6, 60, 140));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpBotonProductos.setBackground(new java.awt.Color(6, 60, 130));
        jpBotonProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpBotonProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBotonProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBotonProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBotonProductosMouseExited(evt);
            }
        });
        jpBotonProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRODUCTOS");
        jpBotonProductos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 320, 20));

        jPanel1.add(jpBotonProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 320, 70));

        jpBotonConsultas.setBackground(new java.awt.Color(6, 60, 130));
        jpBotonConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpBotonConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBotonConsultasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBotonConsultasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBotonConsultasMouseExited(evt);
            }
        });
        jpBotonConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CONSULTAS");
        jpBotonConsultas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 27, 310, -1));

        jPanel1.add(jpBotonConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 320, 70));

        jpBotonProveedores.setBackground(new java.awt.Color(6, 60, 130));
        jpBotonProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpBotonProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBotonProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBotonProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBotonProveedoresMouseExited(evt);
            }
        });
        jpBotonProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PROVEEDORES");
        jpBotonProveedores.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 18, 320, 30));

        jPanel1.add(jpBotonProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 320, 70));

        jpBotonCompra.setBackground(new java.awt.Color(6, 60, 130));
        jpBotonCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpBotonCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBotonCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBotonCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBotonCompraMouseExited(evt);
            }
        });
        jpBotonCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("COMPRA DE PRODUCTOS");
        jpBotonCompra.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 320, 30));

        jPanel1.add(jpBotonCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 320, 70));

        menuPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 320, 520));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        PanelProveedores.setBackground(new java.awt.Color(255, 255, 255));
        PanelProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("PROVEEDORES");
        PanelProveedores.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 291, -1));

        jTabbedPane1.addTab("Proveedores", PanelProveedores);

        PanelCompra.setBackground(new java.awt.Color(255, 255, 255));
        PanelCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Compra");
        PanelCompra.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 291, -1));

        jTabbedPane1.addTab("Compra de Productos", PanelCompra);

        PanelConsultas.setBackground(new java.awt.Color(255, 255, 255));
        PanelConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Consultas", PanelConsultas);

        PanelProducto.setBackground(new java.awt.Color(255, 255, 255));
        PanelProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("________________________________________________________________");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PanelProducto.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 460, 30));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("_________________________________");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PanelProducto.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 240, 30));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("NOMBRE DEL PRODUCTO:");
        PanelProducto.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, -1));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("DESCRIPCION:");
        PanelProducto.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("PRECIO:");
        PanelProducto.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("STOCK:");
        PanelProducto.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 50, -1));

        jtidProducto.setBackground(new java.awt.Color(255, 255, 255));
        jtidProducto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtidProducto.setBorder(null);
        jtidProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtidProductoActionPerformed(evt);
            }
        });
        PanelProducto.add(jtidProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 70, -1));

        jtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jtDescripcion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtDescripcion.setBorder(null);
        jtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDescripcionActionPerformed(evt);
            }
        });
        PanelProducto.add(jtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 450, -1));

        jtNombreProducto.setBackground(new java.awt.Color(255, 255, 255));
        jtNombreProducto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtNombreProducto.setBorder(null);
        jtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreProductoActionPerformed(evt);
            }
        });
        PanelProducto.add(jtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 220, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("__________");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PanelProducto.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 70, 30));

        jtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        jtPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtPrecio.setBorder(null);
        jtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPrecioActionPerformed(evt);
            }
        });
        PanelProducto.add(jtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 70, -1));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("__________");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PanelProducto.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 70, 30));

        jtStock.setBackground(new java.awt.Color(255, 255, 255));
        jtStock.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtStock.setBorder(null);
        jtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtStockActionPerformed(evt);
            }
        });
        PanelProducto.add(jtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 70, -1));

        jtablaProducto.setBackground(new java.awt.Color(255, 255, 255));
        jtablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtablaProducto);

        PanelProducto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 830, 110));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono32.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelProducto.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 80, 60));

        jCEstado.setBackground(new java.awt.Color(255, 255, 255));
        jCEstado.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jCEstado.setForeground(new java.awt.Color(0, 0, 0));
        jCEstado.setText("ESTADO");
        PanelProducto.add(jCEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jTabbedPane1.addTab("Producto", PanelProducto);

        menuPrincipal.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 830, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpBotonProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonProductosMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jpBotonProductosMouseClicked

    private void jpBotonProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonProductosMouseEntered
       jpBotonProductos.setBackground(new Color(6, 45, 115));
    }//GEN-LAST:event_jpBotonProductosMouseEntered

    private void jpBotonProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonProductosMouseExited
       jpBotonProductos.setBackground(new Color(6, 60, 130));
    }//GEN-LAST:event_jpBotonProductosMouseExited

    private void jpBotonProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonProveedoresMouseEntered
       jpBotonProveedores.setBackground(new Color(6, 45, 115));
    }//GEN-LAST:event_jpBotonProveedoresMouseEntered

    private void jpBotonProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonProveedoresMouseExited
       jpBotonProveedores.setBackground(new Color(6, 60, 130));
    }//GEN-LAST:event_jpBotonProveedoresMouseExited

    private void jpBotonCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonCompraMouseEntered
         jpBotonCompra.setBackground(new Color(6, 45, 115));
    }//GEN-LAST:event_jpBotonCompraMouseEntered

    private void jpBotonCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonCompraMouseExited
        jpBotonCompra.setBackground(new Color(6, 60, 130));
    }//GEN-LAST:event_jpBotonCompraMouseExited

    private void jpBotonConsultasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonConsultasMouseEntered
        jpBotonConsultas.setBackground(new Color(6, 45, 115));
    }//GEN-LAST:event_jpBotonConsultasMouseEntered

    private void jpBotonConsultasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonConsultasMouseExited
        jpBotonConsultas.setBackground(new Color(6, 60, 130));
    }//GEN-LAST:event_jpBotonConsultasMouseExited

    private void jpBotonProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonProveedoresMouseClicked
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jpBotonProveedoresMouseClicked

    private void jpBotonCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonCompraMouseClicked
       jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jpBotonCompraMouseClicked

    private void jpBotonConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonConsultasMouseClicked
         jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jpBotonConsultasMouseClicked

    private void jtidProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtidProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtidProductoActionPerformed

    private void jtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDescripcionActionPerformed

    private void jtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreProductoActionPerformed

    private void jtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPrecioActionPerformed

    private void jtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtStockActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           String nombreProducto = jtNombreProducto.getText();
           String descripcion = jtDescripcion.getText();
           int stock = Integer.parseInt(jtStock.getText());
           double precio=Double.parseDouble(jtPrecio.getText());
           boolean activo=jCEstado.isSelected();
           
           Producto producto = new Producto(nombreProducto,descripcion,precio,stock,activo);
           ProductoData pro = new ProductoData();
           pro.guardarProducto(producto);
           
           jtNombreProducto.setText("");
           jtDescripcion.setText("");
           jtStock.setText("");
           jtPrecio.setText("");
           jCEstado.setSelected(false);
           modelo.setRowCount(0);
           cargarTabla();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCompra;
    private javax.swing.JPanel PanelConsultas;
    private javax.swing.JPanel PanelProducto;
    private javax.swing.JPanel PanelProveedores;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpBotonCompra;
    private javax.swing.JPanel jpBotonConsultas;
    private javax.swing.JPanel jpBotonProductos;
    private javax.swing.JPanel jpBotonProveedores;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtNombreProducto;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtStock;
    private javax.swing.JTable jtablaProducto;
    private javax.swing.JTextField jtidProducto;
    private javax.swing.JPanel menuPrincipal;
    // End of variables declaration//GEN-END:variables

public void cargarTabla(){
    ProductoData pro = new ProductoData();

   for (Producto producto : pro.listaProductos()) {

            modelo.addRow(new Object[]{
               producto.getIdProducto(),
                producto.getNombreProducto(),
                producto.getDescripcion(),
                producto.getPrecioActual(),
                producto.getStock(),
                producto.isEstado()});
            

        
            }

}

 private void cargarCabezera() {

        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio Actual");
        modelo.addColumn("Stock");
        modelo.addColumn("Estado");
       jtablaProducto.setModel(modelo);

    }

}
